name: Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: erivelto21/ci-templates/.github/workflows/publish-image.yml@main
    with:
      build_context: .
    secrets: inherit

  deploy:
    needs: publish
    uses: erivelto21/ci-templates/.github/workflows/deploy-kubernetes.yml@main
    with:
      chart_path: charts/api
      release_name: api
      namespace: production
      values_file: charts/api/values.secret.yaml
    secrets: inherit
