name: Publish image

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    uses: erivelto21/ci-templates/.github/workflows/publish-image.yml@main
    with:
      build_context: .
    secrets: inherit
