name: Publish image

on:
  push:
    branches:
      - main

jobs:
  publish-image:
    uses: erivelto21/ci-templates/.github/workflows/publish-image.yml@main
    with:
      registry: ${{ vars.REGISTRY }}
      namespace: ${{ vars.REGISTRY_NAMESPACE }}
      image_name: read-tracker
      dockerfile_path: docker/Dockerfile.api
      build_context: .
    secrets:
      registry_username: ${{ secrets.REGISTRY_USERNAME }}
      registry_password: ${{ secrets.REGISTRY_PASSWORD }}
